### ISSUE TITLE
: Uncaught Error: Class 'tamara\Configuration' not found 

### ISSUE THREAD

**Issue by mub009** [tamara-solution/php-sdk#5]
couldn't call Configuration ..i share my code

<?php
require_once 'vendor/autoload.php';

use tamara\Configuration;
use tamara\Client;
use tamara\Model\Order\Order;
use tamara\Model\Money;
use tamara\Model\Order\Address;
use tamara\Model\Order\Consumer;
use tamara\Model\Order\MerchantUrl;
use tamara\Model\Order\OrderItemCollection;
use tamara\Model\Order\OrderItem;
use tamara\Model\Order\Discount;
use tamara\Request\Checkout\CreateCheckoutRequest;

$Configuration = new Configuration();

[?>
![Capture](https://user-images.githubusercontent.com/25739090/161747500-0b455020-5b20-4b5d-8172-40acb0a4fb92.PNG)

**Comment by tamara-solution** [comment]
Can you please share your index.php code?
