### ISSUE TITLE
this SDK not work with php 8

### ISSUE THREAD

**Issue by ibrahimanm** [tamara-solution/php-sdk#8]
I tried to add this package on my project that use php8  when I write the command the error  I get is :

     - tamara-solution/php-sdk[v1.0.0, ..., 1.2.7] require php ^7.1.0 -> your php version (8.0.3) does not satisfy that requirement.

**Comment by tamara-solution** [comment]
Hi @ibrahimanm from the composer.json we can see that it supports php8 https://github.com/tamara-solution/php-sdk/blob/master/composer.json#L20

Which tamara php-sdk version are you using?

**Comment by tamara-solution** [comment]
We found 1 issue with phpunit wich doesn't match php8, can you please try the latest version now? 1.3.12?

**Comment by ibrahimanm** [comment]
Its still not working , I am using Laravel 9 and php 8
The new error is :
    - tamara-solution/php-sdk 1.3.12 requires symfony/http-foundation ^4.1|^5.0 -> satisfiable by symfony/http-foundation[v4.1.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev].

@tamara-solution

**Comment by tamara-solution** [comment]
@ibrahimanm can you please check with the latest version? 1.13.14
