### ISSUE TITLE
How do I get a token

### ISSUE THREAD

**Issue by turkidkil** [tamara-solution/php-sdk#9]
How do I get a token
I entered the following link  https://partners-sandbox.tamara.co/

But there is no sign up

![Screen Shot 2022-08-20 at 9 10 43 AM](https://user-images.githubusercontent.com/5092858/185731721-2435b2f1-fd43-43bf-900c-f21a51fe494d.png)

**Comment by tamara-solution** [comment]
Please contact our Partner Success Team here https://tamara.com/en/partners.html

**Comment by turkidkil** [comment]
I contacted them but there is no answer! Very bad technical support

**Comment by tamara-solution** [comment]
@turkidkil which merchant/vendor are you working for? This requires a commercial contract before starting the integration.

**Comment by turkidkil** [comment]
I have an app in development
Not yet published
I want to at least check that Tamara's service is working properly
It is not reasonable that you do not have a test account for developers
I don't want an active account
I just want test account :(

**Comment by tamara-solution** [comment]
Oh so sorry, we don't have a test account yet. The sandbox account is only created after the commercial contract is completed as far as I know.
